version: 2.1
# Use a package of configuration called an orb.
# orbs:
# Choose either one of the orbs below
# welcome: circleci/welcome-orb@0.4.1
# aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["0b:dd:ac:f7:58:30:0b:58:67:86:0b:81:4d:65:3a:f6"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - configure_infrastructure
      # - myjob2
