version: 2.1
# Use a package of configuration called an orb.
# orbs:
# Choose either one of the orbs below
# welcome: circleci/welcome-orb@0.4.1
# aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
  configure_website:
    docker:
      - image: python:3.7-alpine3.11
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo "[all]" inventory
      - run:
          name: get ec2 ip
          command: |
            aws ec2 describe-instances  \
            --query 'Reservations[*].Instances[*].PublicIpAddress'  \
            --output text >> inventory
      - add_ssh_keys:
          fingerprints: ["0b:dd:ac:f7:58:30:0b:58:67:86:0b:81:4d:65:3a:f6"]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      # - run:
      #     command: chmod 744 inventory
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook main.yml

# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_website:
          requires:
            - create_infrastructure
      # - myjob2
